### ISSUE TITLE
TabbedPage

### ISSUE THREAD

**Issue by felagund18** [nativecode-dev/oss-xamarin#26] opened 2015-06-25 11:08 UTC
Hi, first, i have to say that this is a great project :).

I am wondering that tabbedPage is acting kind of weird.
TabbedPage is looking normal at portrait mode

![device-2015-06-25-200041](https://cloud.githubusercontent.com/assets/1384327/8353167/14b2a2d6-1af0-11e5-914e-de26dfadeb60.png)

But in landscape mode, tabs should be under the NavBar(Toolbar, or ActionBar) right?

![device-2015-06-25-200113](https://cloud.githubusercontent.com/assets/1384327/8353168/1a6d9316-1af0-11e5-8390-a89ff5d2ab03.png)

**Comment by mikepham** [comment] 2015-06-25 21:54
That's definitely a bug. I hadn't tested with changing orientation. I'll take a look this weekend.

**Comment by mikepham** [comment] 2015-06-25 22:14
Can you describe how you have your pages laid out? I'm assuming it's the following?

MasterDetailPage
- Detail = TabbedPage
- Master = Menu

**Comment by mikepham** [comment] 2015-06-26 04:25
So I looked into this further and it appears to be correct in how it's working now. If you disable the AppCompat package and return to normal Xamarin.Forms implementations, you get the same behavior.

The issue is that AppCompat activities (and this goes for any activity that uses the SupportActionBar) behave the way they do pre-21. Since tab management from ActionBar has been deprecated, what you're seeing is the old behavior.

If you want the new tab behavior in 21+, you'll have to use the TabLayout control which means creating your own renderer and not using the default TabbedPage.

Since this deviates from the normal Xamarin.Forms abstraction, I'm sorry to say this won't be fixed. The project goal is to maintain the same behaviors for Xamarin.Forms while providing as much Material Design as possible. Please see the Project Goals on the [wiki](https://github.com/nativecode-dev/oss-xamarin/wiki).

**Closed as completed** 2015-07-07 01:49 UTC
Labels: question, wontfix
